version: 2

sources:
    - name: raw
      schema: lewagon_data_analytics
      tables:
        - name: sales
          identifier: raw_gz_sales
          description: "Greenweez sales table"
        - name: product
          identifier: raw_gz_product
          description: "Greenweez product table"
        - name: ship
          identifier: raw_gz_ship
          description: "Greenweez shipping table"
