version: 2

# sources:
#   - name: raw_circle
#     schema: raw_data_circle
#     tables:
#     - name: cc_stock
#       identifier: raw_cc_stock
#       tests:
#         - unique:
#             column_name: "(model || '-' || color || '-' || size)"

# models:
#   - name: stock
#     description: product stock information
#     columns:
#       - name: product_id
#         tests:
#         - unique
#         - not_null
#       - name: size
#         tests:
#           - accepted_values:
#             values: ['XS', 'S', 'M', 'L', 'XL', 'XXL']