version: 2

sources:
  - name: raw
    schema: lewagon_data_analytics
    tables:
    - name: cust
      identifier: gwz_customers
      tests:
        - unique:
            column_name: id

models:
  - name: customers
    description: This table contains customers information
    columns:
      - name: id
        description: The customer id as the primary key of the table
        tests:
        - unique
        - not_null
      - name: name
        description: The customer's first name
      - name: surname
        description: The customer's last name
      - name: creation_date
        description: The date when the customer was created
