version: 2

models:
    - name: customers
      description: "A table containing customer details"
      columns:
        - name: id
          description: "The primary key for this table"
          tests:
            - unique
            - not_null
            - relationships:
                field: customers_id
                to: ref('sales')
        - name: name
          description: "The first name of the customer"
          tests:
            - not_null
        - name: creation_date
          description: "The date when the customer is created"
          tests:
            - not_null
    - name: shipping
      description: "A table containing parcel shipping details"
      columns:
        - name: status
          description: "The status of shipping"
          tests:
            - accepted_values:
                values:
                  - ['In Progress', 'In Transit', 'Delivered', 'Cancelled']
